### ISSUE TITLE
[Question] Load from disco doc

### ISSUE THREAD

**Issue by LindaLawton** [mderriey/TokenRenewal#1]
>var client = new TokenClient("https://localhost:44347/connect/token", "mvc", "mvc");

[L67](https://github.com/mderriey/TokenRenewal/blob/master/src/MvcClient/Startup.cs#L67)

Couldn't the token endpoint be loaded from the discovery doc?

**Comment by mderriey** [comment]
Hi there :wave:

Thanks for your question.
You're right, we could totally get the token endpoint URL from the discovery document.

It could look something like:

```csharp
// Use the discovery client to get the token endpoint
var discoveryClient = new DiscoveryClient("https://localhost:44347");
var document = await discoveryClient.GetAsync();

// Request a new token
var client = new TokenClient(document.TokenEndpoint, "mvc", "mvc");
var response = await client.RequestRefreshTokenAsync(refreshToken);
```

**Comment by mderriey** [comment]
I'm happy to try to help you out, but could you provide more information about what exactly doesn't work as expected?
The solution seemed to run fine with the code that uses the `DiscoveryClient`.

**Comment by mderriey** [comment]
Hey @LindaLawton I'm closing this issue since it's gone silent for a few months.

Feel free to open a new one if you're still having issues.
